### ISSUE TITLE
Registration is not working 

### ISSUE THREAD

**Issue by jonas-amme** [DeepMicroscopy/Exact#121]
There are some dependency related problems. The qt-wsi-registration package still uses a depracated pillow method (PIL.Image.ANTIALIAS) which can be modified easily for better compatibility. The problem is already updated in the respective github repo (https://github.com/ChristianMarzahl/WsiRegistration/pull/9), however there is not yet a new pypi package. A current workaround would be to fix pillow to an older version.

**Comment by ChristianMarzahl** [comment]
Moin @jonas-amme 

Do you have [PyPi](https://pypi.org/)? I could make you a collaborator for the [registration-project](https://pypi.org/project/qt-wsi-registration/) and you can upload a new package version. I will not have time for this before the weekend at the earliest. 

VG; Christian

**Comment by jonas-amme** [comment]
Hi @ChristianMarzahl,

You can find me on pypi  at https://pypi.org/user/jonas_ammeling/. I'd be happy to support. 

LG Jonas

**Comment by maubreville** [comment]
See PR #122, which aims to fix it for now.
