### ISSUE TITLE
Scale bar does not show up any more for non-WSI images

### ISSUE THREAD

**Issue by maubreville** [DeepMicroscopy/Exact#92]
In the current (and the currently deployed version on exact.cs.fau.de) version, the scale bar does not show up any more for non-WSI images.

Demo Example: https://exact.cs.fau.de/annotations/297/

**Comment by ChristianMarzahl** [comment]
Dear Marc,

This is intended behaviour by EXACT. If the image meta-data doesn't contain magnification information, EXACT doesn't show a magnification slider. 
If you know the magnification information, you can set them via the REST-API.

```python
images_api.partial_update_image(id=?, objective_power=40)
```
